---
title: "Volcano plots for chapter 5"
author: "Sunniva Bostrand"
date: '2022-10-10'
output: html_document
---
```{r}
setwd("M:/PhD/")
library(EnhancedVolcano)
library(ggsci)
library(scales)
library(here)
library(dplyr)
```
#set colour palette
```{r}
mypal <- pal_npg("nrc", alpha = 0.7)(10)
mypal2 <-pal_tron("legacy", alpha = 0.7)(7)
mypal3 <- pal_lancet("lanonc", alpha = 0.7)(9)
mypal4 <- pal_simpsons(palette = c("springfield"), alpha = 0.7)(16)
mypal5 <- pal_rickandmorty(palette = c("schwifty"), alpha = 0.7)(6)
mypal6 <- pal_futurama(palette = c("planetexpress"), alpha = 0.7)(5)
mypal7 <- pal_startrek(palette = c("uniform"), alpha = 0.7)(5)
mycoloursP<- c(mypal, mypal2, mypal3, mypal4, mypal5, mypal6, mypal7)
show_col(mycoloursP, labels =F)
```
#mglia
```{r}
CN <- read.csv("M:/PhD/Year 4/10X_HD/06_mglia_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_Mglia_CN.csv")
HC <- read.csv("M:/PhD/Year 4/10X_HD/06_mglia_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_Mglia_HC.csv")
mglia <- rbind(CN, HC)


for(i in 1:length(mglia$mm_clu)){
  mglia$Region[i] <- strsplit(mglia$mm_clu, "_")[[i]][1]
  mglia$Cluster[i] <- strsplit(mglia$mm_clu, "_")[[i]][3]
}

mglia <- mglia[mglia$Cluster == "Violet",]


keyvals.col <- ifelse(
  mglia$Region == "HC", mycoloursP[16],  mycoloursP[18])

names(keyvals.col)[keyvals.col == mycoloursP[16]]<-"HC"
names(keyvals.col)[keyvals.col == mycoloursP[18]]<-"CN"


keyvals.shape <- ifelse(
  mglia$Region == "CN", 17,16)


names(keyvals.shape)[keyvals.shape == 17] <- 'CN'
names(keyvals.shape)[keyvals.shape == 16] <- 'HC'


int_genes <- c("FKBP4","ST13","AHSA1","HSPE1","HSPB1","DNAJB1","DNAJB6","HSPA4L","PPID","HSPA6","HSPH1","CHORDC1","BAG3","HSP90AB1","HSPA1B","DNAJA1","HSPD1","CCT4","DNAJA4","PTGES3","HSPA4","SERPINH1","IER5","SUGT1", "NEDD4L")



p1 <- EnhancedVolcano(mglia,
                lab = mglia$gene,
                x = "avg_log2FC",
                y = "p_val_adj", 
                labSize = 3.5,
                FCcutoff = 0.8,
                pCutoff = 0.05,
                pointSize = 3,
                raster = F,
                #shapeCustom = keyvals.shape,
                colCustom = keyvals.col,
                selectLab = unique(int_genes),
                boxedLabels = T,         
                drawConnectors = T,
                #maxoverlapsConnectors = 3,
                labFace = "bold",
                title = NULL,
                subtitle =NULL,
                legendLabSize = 12,
                legendIconSize = 4,
                legendPosition = "right",
                xlim = c((min(mglia$avg_log2FC) - .05), (max(mglia$avg_log2FC + 0.5)))) 
```


#astros
```{r}
FrCx <- read.csv("M:/PhD/Year 4/10X_HD/07_astros_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_astros_FrCx.csv")
HC <- read.csv("M:/PhD/Year 4/10X_HD/07_astros_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_astros_HC.csv")
astros <- rbind(FrCx, HC)


for(i in 1:length(astros$as_clu)){
  astros$Region[i] <- strsplit(astros$as_clu, "_")[[i]][1]
  astros$Cluster[i] <- strsplit(astros$as_clu, "_")[[i]][3]
}

astros <- astros[astros$Cluster == "5",]


keyvals.col <- ifelse(
  astros$Region == "HC", mycoloursP[16],  mycoloursP[8])

names(keyvals.col)[keyvals.col == mycoloursP[16]]<-"HC"
names(keyvals.col)[keyvals.col == mycoloursP[8]]<-"FrCx"



int_genes <- c("HSPH1", "HSPA1A", "CRYAB","HSP90AA1","PTGES3","CHORDC1","DNAJB1","STIP1","HSPA4L", "HSPH1", "CHORDC1","HSPD1", "CCT4") 



p2 <- EnhancedVolcano(astros,
                lab = astros$gene,
                x = "avg_log2FC",
                y = "p_val_adj", 
                labSize = 3.5,
                FCcutoff = 0.8,
                pCutoff = 0.05,
                pointSize = 3,
                raster = F,
                #shapeCustom = keyvals.shape,
                colCustom = keyvals.col,
                selectLab = unique(int_genes),
                boxedLabels = T,         
                drawConnectors = T,
                #maxoverlapsConnectors = 3,
                labFace = "bold",
                title = NULL,
                subtitle =NULL,
                legendLabSize = 12,
                legendIconSize = 4,
                legendPosition = "right",
                xlim = c((min(astros$avg_log2FC) - .05), (max(astros$avg_log2FC + 0.5)))) 
```


#oligos
```{r}
#FrCx <- read.csv("M:/PhD/Year 4/10X_HD/04_DGE_condition_tissue_split/within_cluster/condition/DE_condition_Oligos_FrCx.csv")
HC <- read.csv("M:/PhD/Year 4/10X_HD/04_DGE_condition_tissue_split/within_cluster/condition/DE_condition_Oligos_HC.csv")
CB <- read.csv("M:/PhD/Year 4/10X_HD/04_DGE_condition_tissue_split/within_cluster/condition/DE_condition_Oligos_CB.csv")
oligos <- rbind(CB, HC)


for(i in 1:length(oligos$ol_clu)){
  oligos$Region[i] <- strsplit(oligos$ol_clu, "_")[[i]][1]
  oligos$Cluster[i] <- strsplit(oligos$ol_clu, "_")[[i]][3]
}

oligos <- oligos[oligos$Cluster == "pine",]


keyvals.col <- ifelse(
  oligos$Region == "HC", mycoloursP[16],  mycoloursP[22])

names(keyvals.col)[keyvals.col == mycoloursP[16]]<-"HC"
names(keyvals.col)[keyvals.col == mycoloursP[22]]<-"CB"



int_genes <- c("HSPA1A", "HSPH1", "CHORDC1","HSPA4L", "DNAJB1", "PTGES3","HSPD1","CRYAB", "CCT4","BAG3","HSPA4","HSPA6", "STIP1", "ST13", "SUGT1", "HSPA8", "HSPA1B") 



p3<- EnhancedVolcano(oligos,
                lab = oligos$gene,
                x = "avg_log2FC",
                y = "p_val_adj", 
                labSize = 3.5,
                FCcutoff = 0.8,
                pCutoff = 0.05,
                pointSize = 3,
                raster = F,
                #shapeCustom = keyvals.shape,
                colCustom = keyvals.col,
                selectLab = unique(int_genes),
                boxedLabels = T,         
                drawConnectors = T,
                #maxoverlapsConnectors = 3,
                labFace = "bold",
                title = NULL,
                subtitle =NULL,
                legendLabSize = 12,
                legendIconSize = 4,
                legendPosition = "right",
                xlim = c((min(oligos$avg_log2FC) - .05), (max(oligos$avg_log2FC + 0.5)))) 
```


#save
```{r}
PlotList<- list()
PlotList[[1]]<-p1
PlotList[[2]]<-p2
PlotList[[3]]<-p3


pdf(here("PhD","Thesis","thesisplots","20221010_volcanoplots_chap5.pdf"), width = 12, height = 6)
print(PlotList)
dev.off()
```