---
title: "Reverse validation of PDE1A"
author: "Sunniva Bostrand"
date: '2022-10-28'
output: html_document
---
#Set directory and load libraries
```{r}
setwd("M:/PhD/")
library(RColorBrewer)
library(ggsci)
library(scales)
library(here)
library(dplyr)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(Seurat)
```

```{r}
#read in
seur_comb <- readRDS("//sg.datastore.ed.ac.uk/cmvm/scs/groups/Williamsdata/Sunniva/HD/datasets/06_swapped/20211005_seur_comb_qc_integrated_annot_swappedsamples.rds")

#subset for #FrCx
seur_comb <- subset(seur_comb, Tissue == "FrCx")

#identify nuclei positive for MBP + any PDE1
all_pos <- WhichCells(object = seur_comb, expression = rna_MBP > 1 & rna_PDE1B > 1 | rna_MBP > 1 & rna_PDE1C > 1 | rna_MBP > 1 & rna_PDE1A > 1, slot = "counts")
#identify nuclei positive for MBP + PDE1A
dpos <- WhichCells(object = seur_comb, expression = rna_MBP > 1 & rna_PDE1A > 1, slot = "counts")
#identify nuclei positive for MBP 
MBP <-  WhichCells(object = seur_comb, expression = rna_MBP > 1 , slot = "counts")
#identify nuclei positive forPDE1A
PDE1A <-  WhichCells(object = seur_comb, expression =  rna_PDE1A > 1, slot = "counts")

#create metadata column to store information above as true/false coded with 1 = T and 0 = F
seur_comb@meta.data$MBP <- ifelse(colnames(seur_comb) %in% MBP, "1", "0")
seur_comb@meta.data$PDE1A <- ifelse(colnames(seur_comb) %in% PDE1A, "1", "0")
seur_comb@meta.data$dpos <- ifelse(colnames(seur_comb) %in% dpos, "1", "0")
seur_comb@meta.data$all_pos <- ifelse(colnames(seur_comb) %in% all_pos, "1", "0")

#extract metadata as df and convert variables to numeric
meta_data <- seur_comb@meta.data 
meta_data$MBP <- as.numeric(meta_data$MBP)
meta_data$PDE1A <- as.numeric(meta_data$PDE1A)
meta_data$dpos <- as.numeric(meta_data$dpos)
meta_data$all_pos <- as.numeric(meta_data$all_pos)

#sum up the total expression counts per sample
tot_MBP <- meta_data %>% group_by(ProcessNumber) %>% 
  summarise(tot_MBP = 
              sum(MBP))
tot_PDE1A <- meta_data %>% group_by(ProcessNumber) %>% 
  summarise(tot_PDE1A = 
              sum(PDE1A))
tot_dpos <- meta_data %>% group_by(ProcessNumber) %>% 
  summarise(tot_dpos = 
              sum(dpos))

tot_allpos <- meta_data %>% group_by(ProcessNumber) %>% 
  summarise(tot_allpos = 
              sum(all_pos))

#create new df by merging this information also with the metadata
df<- merge(tot_MBP, tot_PDE1A, by = "ProcessNumber", all = TRUE)
df<- merge(df, tot_dpos, by = "ProcessNumber", all = TRUE)
df<- merge(df, tot_allpos, by = "ProcessNumber", all = TRUE)
df<- merge (df, meta_data, by = "ProcessNumber", all = TRUE)
df<- df[!duplicated(df$ProcessNumber),]

#calculate proportion of MBP+ nl also +ive for PDE1A
df$prop_dPos <- df$tot_dpos/df$tot_MBP
#calculate proportion of MBP+ nl also +ive for PDE1A, PDE1B or PDE1C
df$prop_allPos <- df$tot_allpos/df$tot_MBP

```

#Plot and save
```{r}
p1 <- ggplot(df, aes(x = donor_status, y = prop_dPos, fill = donor_status)) +
  geom_boxplot()+ geom_jitter(position=position_dodge(width=0.75)) +
  theme_classic() + ylab("Proportion of MBP+ cells also +ive for PDE1A") + xlab("Condition") + 
  scale_fill_manual(values = (brewer.pal(10,"Paired")[5:6])) + theme(axis.text = element_text(size = 20))  +
  theme(axis.title = element_text(size = 25))  + theme(legend.text = element_text(size = 20))  + theme(legend.title = element_text(size = 20)) + ylim(0,1)



p2 <- ggplot(df, aes(x = donor_status, y = prop_allPos, fill = donor_status)) +
  geom_boxplot()+ geom_jitter(position=position_dodge(width=0.75)) +
  theme_classic() + ylab("Proportion of MBP+ cells also +ive for PDE1") + xlab("Condition") + 
  scale_fill_manual(values = (brewer.pal(10,"Paired")[7:8])) + theme(axis.text = element_text(size = 20))  +
  theme(axis.title = element_text(size = 25))  + theme(legend.text = element_text(size = 20))  + theme(legend.title = element_text(size = 20)) + ylim(0,1)


PlotList<- list()
PlotList[[1]]<-p1
PlotList[[2]]<-p2

pdf(here("PhD","Thesis","thesisplots","20221026_MBP_PDE1A_10X_count_v2.pdf"), width = 7, height = 9)
print(PlotList)
dev.off()

```

```{r}

sessionInfo()

```
