---
title: "Analyse PDGFRA/BAG3 RNAscope"
author: "Sunniva Bostrand"
date: '2022-10-15'
output: html_document
---

```{r}
#set path and load libraries
setwd("M:/PhD/")
library(RColorBrewer)
library(ggsci)
library(scales)
library(here)
library(dplyr)
library(dplyr)
library(ggplot2)
library(ggpubr)
```

```{r}
#Read in
dat <- read.csv("M:/PhD/Year 4/Validation/ISH/PDGFRA_BAG3_quant2.csv")

#select detected cells only
dat <- subset(dat, dat$Name =="PathCellObject")

#select only the columns of interest
t <- select(dat, 誰..Image, Parent, Subcellular..Channel.2..Num.spots.estimated, Subcellular..Channel.3..Num.spots.estimated )

#rename columns
colnames(t) [colnames(t)== "Subcellular..Channel.2..Num.spots.estimated"] <- "BAG3_dots"
colnames(t) [colnames(t)== "Subcellular..Channel.3..Num.spots.estimated"] <- "PDGFRa_dots"
t$PDGFRa_dots <- as.numeric(t$PDGFRa_dots)
t$BAG3_dots <- as.numeric(t$BAG3_dots)

#add ID column and region
for(i in 1:length(t$誰..Image)){
  t$ID[i] <- strsplit(t$誰..Image, "_")[[i]][1]
  t$region[i] <- strsplit(t$誰..Image, "_")[[i]][2]
}

#add tissue column
t$tissue <- ifelse(t$Parent == "GM1" | t$Parent == "GM2" | t$Parent == "GM3"| t$Parent == "GM4", "GM", "WM")

#number ROIs
t[,"ROI"] <- NA
t[t$Parent == "GM1", "ROI"] <- "1"
t[t$Parent == "GM2", "ROI"] <- "2"
t[t$Parent == "GM3", "ROI"] <- "3"
t[t$Parent == "GM4", "ROI"] <- "4"
t[t$Parent == "WM1", "ROI"] <- "5"
t[t$Parent == "WM2", "ROI"] <- "6"
t[t$Parent == "WM3", "ROI"] <- "7"
t[t$Parent == "WM4", "ROI"] <- "8"

#select columns again
t<- select(t, ID, tissue, region, ROI, BAG3_dots, PDGFRa_dots)


#Assign unique ID for each FOV - check that this works properly 
split <- split(t, t$ID)
for (i in 1:length(names(split))) {
  temp <-split[[i]]
  temp$FOV <- paste(names(split)[i], temp$ROI)
  if(i == 1){
    t <- temp
  }else{
    t <- rbind(temp, t)}
}

#Add area for calculating density
t$ROI_a_um2 <- "250000"


#Add disease status
t$Condition <- ifelse(t$ID == "1" | t$ID == "2" | t$ID == "5" | t$ID == "6" |t$ID == "10" |t$ID == "12" | t$ID == "3",  "HD", "Ctrl")

#add logical columns 
t<- mutate(t, PDGFRa = t$PDGFRa_dots >=1)
t<- mutate(t, BAG3 = t$BAG3_dots >=1)
t<- mutate(t, dPos= t$BAG3 == TRUE & t$PDGFRa == TRUE)

#save the reduced dataset
#write.csv(t, file = "M:/PhD/Year 4/Validation/ISH/ISH_BAG3_PDGFRa_df2.csv")
```

#alternatively read in from here
```{r}
t <- read.csv("C:/Users/44745/Downloads/ISH_BAG3_PDGFRa_df2.csv")

#sum up positive/double positive cells per FOV
PDGFRa <- t %>% group_by(FOV) %>%
  summarise(tot_PDGFRa = sum(PDGFRa)) 
BAG3 <- t %>% group_by(FOV) %>% summarise(tot_BAG3 = sum(BAG3)) 
dPos <-  t %>% group_by(FOV) %>%
  summarise(tot_dPos = sum(dPos)) 
tot_nl <- t %>% group_by(FOV) %>%
  summarise(tot_nl = length(FOV))



#create df with counts per FOV
df<- merge(BAG3, PDGFRa, by = "FOV", all = TRUE)        
df<- merge(df,dPos, by = "FOV", all = TRUE) 
df <- merge(df, tot_nl, by = "FOV", all = TRUE)
t2 <- merge(df, t, by = "FOV", all = TRUE)

t2<- t2[!duplicated(t2$FOV),]



#express double pos as proportion of PDGFRa-pos
t2$prop_dPos <- t2$tot_dPos/t2$tot_PDGFRa
#percentage
t2$perc_dPos <- as.integer(t2$prop_dPos*100)
#calculate density 
t2$dP_density <- t2$tot_dPos/as.numeric(t2$ROI_a_um2)
t2$PDGFRa_density <- t2$tot_PDGFRa/as.numeric(t2$ROI_a_um2)
t2$BAG3_density <- t2$tot_BAG3/as.numeric(t2$ROI_a_um2)
```

#Statistical analysis
```{r}
#normality test
shapiro.test(t2$prop_dPos)#not normal
#nonparam t/test
res <- wilcox.test(t2$prop_dPos~ t2$Condition, paired = FALSE, conf.int = T, conf.level = 0.95)
print(res)
p_value <- res$p.value
statistic <- res$statistic
```

#Plot and save
```{r}
t2$Myelinated <- ifelse(t2$tissue == "WM", t2$Myelinated <- "Y", "N")

#p1 <-  ggplot(t2, aes(x = Condition, y = prop_dPos, fill = Myelinated)) +
 # geom_boxplot()+ geom_jitter(position=position_dodge(width=0.75)) +
  #theme_classic() + ylab("Proportion of PDGFRa+ cells also +ive for BAG3") + xlab("Condition") + 
  #scale_fill_manual(values = (brewer.pal(4,"Paired"))) + theme(axis.text = element_text(size = 20))  +
  #theme(axis.title = element_text(size = 25))  + theme(legend.text = element_text(size = 20))  + theme(legend.title = #element_text(size = 20)) + ylim(0,1) 


p2<-ggplot(t2, aes(x = Condition, y = prop_dPos, fill = Condition)) +
  geom_boxplot()+ geom_jitter(position=position_dodge(width=0.75)) +
  theme_classic() + ylab("Proportion of PDGFRa+ cells also +ive for BAG3") + xlab("Condition") + 
  scale_fill_manual(values = (brewer.pal(10,"Paired")[3:4])) + theme(axis.text = element_text(size = 20))  +
  theme(axis.title = element_text(size = 25))  + theme(legend.text = element_text(size = 20))  + theme(legend.title = element_text(size = 20)) + ylim(0,1)



#p3<- ggplot(t2, aes(x = Myelinated, y = prop_dPos, fill = Myelinated)) +
 # geom_boxplot()+ geom_jitter(position=position_dodge(width=0.75)) +
  #theme_classic() + ylab("Proportion of PDGFRa+ cells also +ive for BAG3") + xlab("Myelinated") + 
  #scale_fill_manual(values = (brewer.pal(13,"Paired")[9:11])) + theme(axis.text = element_text(size = 20))  +
  #theme(axis.title = element_text(size = 25))  + theme(legend.text = element_text(size = 20))  + theme(legend.title = #element_text(size = 20)) + ylim(0,1)

#PlotList<- list()
#PlotList[[1]]<-p1
#PlotList[[2]]<-p2
#PlotList[[3]]<-p3

pdf("C:/Users/44745/Downloads/20231129_BAG3_PDGFRA_barplots_colour_new.pdf", width = 7, height = 9)
print(p2)
dev.off()

```
