---
title: "Plot venn diagrams to show overlap in DE genes"
author: "Sunniva Bostrand"
date: '2022-08-15'
output: html_document
---

```{r}
library(ggvenn)
```

#venn diagram to show shared marker genes between thyme, violet and pine
```{r}
mglia <- read.csv("M:/PhD/Year 4/10X_HD/06_mglia_out/Mglia_markers/mark_genes_res05/fil_markmm_clusters_named.csv")
astros <- read.csv("M:/PhD/Year 4/10X_HD/07_astros_out/astros_markers/mark_genes_res05/fil_markas_clusters_named.csv")
oligos <- read.csv("M:/PhD/Year 4/10X_HD/02_Oligo_markers/mark_genes_res05/fil_markol_clusters_named.csv")

pine <- subset(oligos, oligos$cluster == "OPC_pine")
thyme <- subset(astros, astros$cluster == "Astro_5")
violet <- subset(mglia, mglia$cluster == "MM_Violet")
x <- list(Astro_Thyme = thyme$gene, Mglia_Violet = violet$gene, OPC_Pine = pine$gene)

ggvenn(x, show_percentage = F, fill_color = c("#EFC000FF", "#868686FF", "#CD534CFF"), stroke_size = 0.5, set_name_size = 8, text_size = 9)
a <- venn(x)
intersections<-attr(a,"intersections")
shared <- intersections$`Astro_Thyme:Mglia_Violet:OPC_Pine`
write.csv(shared, "shared.csv")
```

#venn diagram to show regional differences in DGEs with disease for each cell type 
#ENs
```{r}
CB <- read.csv("M:/PhD/Year 4/10X_HD/09_ENs_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_ENs_CB.csv")
CN <- read.csv("M:/PhD/Year 4/10X_HD/09_ENs_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_ENs_CN.csv")
HC <- read.csv("M:/PhD/Year 4/10X_HD/09_ENs_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_ENs_HC.csv")
FrCx <- read.csv("M:/PhD/Year 4/10X_HD/09_ENs_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_ENs_FrCx.csv")
x <- list(CB = CB$gene, CN = CN$gene, HC = HC$gene, FrCx = FrCx$gene)
p1 <- ggvenn(x, show_percentage = F, fill_color = c("#0073C2FF", "#EFC000FF", "#868686FF", "#CD534CFF"), stroke_size = 0.5, set_name_size = 8, text_size = 8)
```


#INs
```{r}
CB <- read.csv("M:/PhD/Year 4/10X_HD/10_INs_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_INs_CB.csv")
CN <- read.csv("M:/PhD/Year 4/10X_HD/10_INs_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_INs_CN.csv")
HC <- read.csv("M:/PhD/Year 4/10X_HD/10_INs_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_INs_HC.csv")
FrCx <- read.csv("M:/PhD/Year 4/10X_HD/10_INs_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_INs_FrCx.csv")
y <- list(CB = CB$gene, CN = CN$gene, HC = HC$gene, FrCx = FrCx$gene)
p2 <- ggvenn(y, show_percentage = F, fill_color = c("#0073C2FF", "#EFC000FF", "#868686FF", "#CD534CFF"), stroke_size = 0.5, set_name_size = 8, text_size = 8)
```

#mglia
```{r}
CB <- read.csv("M:/PhD/Year 4/10X_HD/06_mglia_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_Mglia_CB.csv")
CN <- read.csv("M:/PhD/Year 4/10X_HD/06_mglia_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_Mglia_CN.csv")
HC <- read.csv("M:/PhD/Year 4/10X_HD/06_mglia_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_Mglia_HC.csv")
FrCx <- read.csv("M:/PhD/Year 4/10X_HD/06_mglia_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_Mglia_FrCx.csv")
z <- list(CB = CB$gene, CN = CN$gene, HC = HC$gene, FrCx = FrCx$gene)
p3 <- ggvenn(z, show_percentage = F, fill_color = c("#0073C2FF", "#EFC000FF", "#868686FF", "#CD534CFF"), stroke_size = 0.5, set_name_size = 8, text_size = 8)
```

#astros
```{r}
CB <- read.csv("M:/PhD/Year 4/10X_HD/07_astros_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_astros_CB.csv")
CN <- read.csv("M:/PhD/Year 4/10X_HD/07_astros_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_astros_CN.csv")
HC <- read.csv("M:/PhD/Year 4/10X_HD/07_astros_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_astros_HC.csv")
FrCx <- read.csv("M:/PhD/Year 4/10X_HD/07_astros_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_astros_FrCx.csv")
w <- list(CB = CB$gene, CN = CN$gene, HC = HC$gene, FrCx = FrCx$gene)
p4 <- ggvenn(w, show_percentage = F, fill_color = c("#0073C2FF", "#EFC000FF", "#868686FF", "#CD534CFF"), stroke_size = 0.5, set_name_size = 8, text_size = 8)
```

#endoperi
```{r}
CB <- read.csv("M:/PhD/Year 4/10X_HD/08_endoperi_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_endoperi_CB.csv")
CN <- read.csv("M:/PhD/Year 4/10X_HD/08_endoperi_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_endoperi_CN.csv")
HC <- read.csv("M:/PhD/Year 4/10X_HD/08_endoperi_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_endoperi_HC.csv")
FrCx <- read.csv("M:/PhD/Year 4/10X_HD/08_endoperi_out/DGE_condition_tissue_split/within_cluster/condition/DE_condition_endoperi_FrCx.csv")
v <- list(CB = CB$gene, CN = CN$gene, HC = HC$gene, FrCx = FrCx$gene)

p5 <- ggvenn(v, show_percentage = F, fill_color = c("#0073C2FF", "#EFC000FF", "#868686FF", "#CD534CFF"), stroke_size = 0.5, set_name_size = 8, text_size = 8)
```

#oligos
```{r}
CN <- read.csv("M:/PhD/Year 4/10X_HD/04_DGE_condition_tissue_split/within_cluster/condition/DE_condition_Oligos_CN.csv")
HC <- read.csv("M:/PhD/Year 4/10X_HD/04_DGE_condition_tissue_split/within_cluster/condition/DE_condition_Oligos_HC.csv")
FrCx <- read.csv("M:/PhD/Year 4/10X_HD/04_DGE_condition_tissue_split/within_cluster/condition/DE_condition_Oligos_FrCx.csv")
CB <- read.csv("M:/PhD/Year 4/10X_HD/04_DGE_condition_tissue_split/within_cluster/condition/DE_condition_Oligos_CB.csv")
u <- list( CN = CN$gene, HC = HC$gene, FrCx = FrCx$gene, CB = CB$gene)
venn(u)

p6 <- ggvenn(u, show_percentage = F, fill_color = c("#EFC000FF", "#868686FF", "#CD534CFF"), stroke_size = 0.5, set_name_size = 8, text_size = 8)

```

#save plots 
```{r}
PlotList<- list()
PlotList[[1]]<-p1
PlotList[[2]]<-p2
PlotList[[3]]<-p3
PlotList[[4]]<-p4
PlotList[[5]]<-p5
PlotList[[6]]<-p6

pdf(here("PhD","Thesis","thesisplots","20220815_vennplots.pdf"), width = 7, height = 6)
print(PlotList)
dev.off()
```

```{r}
SessionInfo()
```
