---
title: "Volcano plots"
author: "Sunniva Bostrand"
date: '2022-08-12'
output: html_document
---
```{r}
setwd("M:/PhD/")
library(EnhancedVolcano)
library(ggsci)
library(scales)
library(here)
library(dplyr)
```
#set colour palette
```{r}
mypal <- pal_npg("nrc", alpha = 0.7)(10)
mypal2 <-pal_tron("legacy", alpha = 0.7)(7)
mypal3 <- pal_lancet("lanonc", alpha = 0.7)(9)
mypal4 <- pal_simpsons(palette = c("springfield"), alpha = 0.7)(16)
mypal5 <- pal_rickandmorty(palette = c("schwifty"), alpha = 0.7)(6)
mypal6 <- pal_futurama(palette = c("planetexpress"), alpha = 0.7)(5)
mypal7 <- pal_startrek(palette = c("uniform"), alpha = 0.7)(5)
mycoloursP<- c(mypal, mypal2, mypal3, mypal4, mypal5, mypal6, mypal7)
show_col(mycoloursP, labels =F)
```
#read in DGE data
```{r}
mglia <- read.csv("M:/PhD/Year 4/10X_HD/06_mglia_out/DGE_condition_tissue_split/within_cluster/condition/Mglia_condition_DEGs.csv")
oligos <- read.csv("M:/PhD/Year 4/10X_HD/04_DGE_condition_tissue_split/within_cluster/condition/Oligos_condition_DEGs.csv")
INs <- read.csv("M:/PhD/Year 4/10X_HD/10_INs_out/DGE_condition_tissue_split/within_cluster/condition/INs_condition_DEGs.csv")
ENs <- read.csv("M:/PhD/Year 4/10X_HD/09_ENs_out/DGE_condition_tissue_split/within_cluster/condition/ENs_condition_DEGs.csv")
astros <- read.csv("M:/PhD/Year 4/10X_HD/07_astros_out/DGE_condition_tissue_split/within_cluster/condition/astros_condition_DEGs.csv")
#vasc <- read.csv("M:/PhD/Year 4/10X_HD/08_endoperi_out/DGE_condition_tissue_split/within_cluster/condition/endoperi_condition_DEGs.csv")
```
#mglia
```{r}
#mglia

for(i in 1:length(mglia$mm_clu)){
  mglia$Region[i] <- strsplit(mglia$mm_clu, "_")[[i]][1]
  mglia$Cluster[i] <- strsplit(mglia$mm_clu, "_")[[i]][3]
}

keyvals.col <- ifelse(
  mglia$Cluster == "Daisy", mycoloursP[10],
  ifelse(mglia$Cluster == "Lily", mycoloursP[11],
         ifelse(mglia$Cluster =="Orchid", mycoloursP[12],
                ifelse(mglia$Cluster =="Pansy", mycoloursP[24],
                       ifelse(mglia$Cluster == "Rose", mycoloursP[14],
                              ifelse(mglia$Cluster == "Tulip", mycoloursP[26],
                                    mycoloursP[16]  ))))))

names(keyvals.col)[keyvals.col == mycoloursP[10]] <- 'Mglia_Daisy'
names(keyvals.col)[keyvals.col == mycoloursP[11]] <- 'Mglia_Lily'
names(keyvals.col)[keyvals.col == mycoloursP[12]] <- "BAMs"
names(keyvals.col)[keyvals.col == mycoloursP[24]] <- "Mglia_Pansy"
names(keyvals.col)[keyvals.col == mycoloursP[14]]<-"Mglia_Rose"
names(keyvals.col)[keyvals.col == mycoloursP[26]]<-"Mglia_Tulip"
names(keyvals.col)[keyvals.col == mycoloursP[16]]<-"Mglia_Violet"

keyvals.shape <- ifelse(
  mglia$Region == "CN", 17,
  ifelse(mglia$Region == "HC", 16,
         ifelse(mglia$Region == "FrCx", 15, 18 )))
  
names(keyvals.shape)[keyvals.shape == 15] <- 'FrCx'
names(keyvals.shape)[keyvals.shape == 17] <- 'CN'
names(keyvals.shape)[keyvals.shape == 16] <- 'HC'
names(keyvals.shape)[keyvals.shape == 18] <- 'CB'

#plot with no labels
p1 <-EnhancedVolcano(mglia,
                lab = NA,
                x = "avg_log2FC",
                y = "p_val_adj", 
                labSize = 3.5,
                FCcutoff = 0.8,
                pCutoff = 0.05,
                raster = F,
                shapeCustom = keyvals.shape,
                colCustom = keyvals.col,
                #selectLab = top5,
                #boxedLabels = T,         
                #drawConnectors = T,
                #labFace = "bold",
                title = NULL,
                subtitle =NULL,
                legendLabSize = 12,
                legendIconSize = 4,
                legendPosition = "right",
                xlim = c((min(mglia$avg_log2FC) - .05), (max(mglia$avg_log2FC + 0.5))))

top5 <- mglia %>% top_n(5, abs(avg_log2FC))
for (i in 1:length(mglia$X.1)){
  ifelse(mglia$X.1[i] %in% top5$X.1 == TRUE, mglia$X.1[i] <- mglia$gene[i], mglia$X.1[i] <- mglia$X.1[i])
}

top5$X.1 <- top5$gene

#plot with labels
p2 <- EnhancedVolcano(mglia,
                lab = mglia$X.1,
                x = "avg_log2FC",
                y = "p_val_adj", 
                labSize = 3.5,
                FCcutoff = 0.8,
                pCutoff = 0.05,
                pointSize = 3,
                raster = F,
                shapeCustom = keyvals.shape,
                colCustom = keyvals.col,
                selectLab = top5$X.1,
                boxedLabels = T,         
                drawConnectors = T,
                #maxoverlapsConnectors = 3,
                labFace = "bold",
                title = NULL,
                subtitle =NULL,
                legendLabSize = 12,
                legendIconSize = 4,
                legendPosition = "right",
                xlim = c((min(mglia$avg_log2FC) - .05), (max(mglia$avg_log2FC + 0.5)))) 
top5


```

#astros
```{r}
for(i in 1:length(astros$as_clu)){
  astros$Region[i] <- strsplit(astros$as_clu, "_")[[i]][1]
  astros$Cluster[i] <- strsplit(astros$as_clu, "_")[[i]][3]
}



keyvals.col <- ifelse(
  astros$Cluster == "1", mycoloursP[10],
  ifelse(astros$Cluster == "2", mycoloursP[11],
         ifelse(astros$Cluster =="3", mycoloursP[12],
                ifelse(astros$Cluster =="4", mycoloursP[24],
                       ifelse(astros$Cluster == "5", mycoloursP[14],
                              ifelse(astros$Cluster == "6", mycoloursP[26],
                                     mycoloursP[16]))))))

names(keyvals.col)[keyvals.col == mycoloursP[10]] <- 'Astro_Mint'
names(keyvals.col)[keyvals.col == mycoloursP[11]] <- 'Astro_Basil'
names(keyvals.col)[keyvals.col == mycoloursP[12]] <- "Astro_Chives"
names(keyvals.col)[keyvals.col == mycoloursP[24]] <- "Astro_Sage"
names(keyvals.col)[keyvals.col == mycoloursP[14]]<-"Astro_Thyme"
names(keyvals.col)[keyvals.col == mycoloursP[26]]<-"Astro_Chervil"
names(keyvals.col)[keyvals.col == mycoloursP[16]]<-"Astro_Oligo"

keyvals.shape <- ifelse(
  astros$Region == "CN", 17,
  ifelse(astros$Region == "HC", 16,
         ifelse(astros$Region == "FrCx", 15, 18 )))

names(keyvals.shape)[keyvals.shape == 15] <- 'FrCx'
names(keyvals.shape)[keyvals.shape == 17] <- 'CN'
names(keyvals.shape)[keyvals.shape == 16] <- 'HC'
names(keyvals.shape)[keyvals.shape == 18] <- 'CB'

#no labels
p3 <- EnhancedVolcano(astros,
                lab = NA,
                x = "avg_log2FC",
                y = "p_val_adj", 
                labSize = 3.5,
                FCcutoff = 0.8,
                pCutoff = 0.05,
                pointSize = 3,
                raster = F,
                shapeCustom = keyvals.shape,
                colCustom = keyvals.col,
                #selectLab = top5$X.1,
                #boxedLabels = T,         
                #drawConnectors = T,
                #labFace = "bold",
                title = NULL,
                subtitle =NULL,
                legendLabSize = 12,
                legendIconSize = 4,
                legendPosition = "right",
                xlim = c((min(astros$avg_log2FC) - .05), (max(astros$avg_log2FC + 0.5))))

#get labels for only the top 5 ***data point** (not the same as top 5 genes)
top5 <- astros %>% top_n(5, abs(avg_log2FC))
for (i in 1:length(astros$X.1)){
  ifelse(astros$X.1[i] %in% top5$X.1 == TRUE, astros$X.1[i] <- astros$gene[i], astros$X.1[i] <- astros$X.1[i])
}

top5$X.1 <- top5$gene

#with labels
p4 <- EnhancedVolcano(astros,
                lab = astros$X.1,
                x = "avg_log2FC",
                y = "p_val_adj", 
                labSize = 3.5,
                FCcutoff = 0.8,
                pCutoff = 0.05,
                pointSize = 3,
                raster = F,
                shapeCustom = keyvals.shape,
                colCustom = keyvals.col,
                selectLab = top5$X.1,
                boxedLabels = T,         
                drawConnectors = T,
                labFace = "bold",
                title = NULL,
                subtitle =NULL,
                legendLabSize = 12,
                legendIconSize = 4,
                legendPosition = "right",
                xlim = c((min(astros$avg_log2FC) - .05), (max(astros$avg_log2FC + 0.5))))

top5
```

##oligos
```{r}
for(i in 1:length(oligos$ol_clu)){
  oligos$Region[i] <- strsplit(oligos$ol_clu, "_")[[i]][1]
  oligos$Cluster[i] <- strsplit(oligos$ol_clu, "_")[[i]][3]
}

ggplot(oligos, aes(avg_log2FC, -log10(p_val_adj), label = gene, col = Cluster, shape = Region)) + 
  geom_point(size = 2) + geom_hline(yintercept = 1, aes(linetype = dashed)) + theme_classic() + scale_colour_manual(values = mycoloursP[10:40])


keyvals.col <- ifelse(
  oligos$Cluster == "apple", mycoloursP[10],
  ifelse(oligos$Cluster == "ash", mycoloursP[11],
         ifelse(oligos$Cluster =="birch", mycoloursP[12],
         ifelse(oligos$Cluster =="cedar", mycoloursP[24],
                ifelse(oligos$Cluster == "cherry", mycoloursP[14],
                       ifelse(oligos$Cluster == "elder", mycoloursP[26],
                              ifelse(oligos$Cluster =="fir", mycoloursP[16],
                                     ifelse(oligos$Cluster =="maple", mycoloursP[17],
                                            ifelse(oligos$Cluster == "oak", mycoloursP[18],
                                                   ifelse(oligos$Cluster == "pine", mycoloursP[19], mycoloursP[22]
                                                          ))))))))))

names(keyvals.col)[keyvals.col == mycoloursP[10]] <- 'COP_Apple'
names(keyvals.col)[keyvals.col == mycoloursP[11]] <- 'Oligo_Ash'
names(keyvals.col)[keyvals.col == mycoloursP[12]] <- "Oligo_Birch"
names(keyvals.col)[keyvals.col == mycoloursP[24]] <- "Oligo_Cedar"
names(keyvals.col)[keyvals.col == mycoloursP[14]]<-"COP_Cherry"
names(keyvals.col)[keyvals.col == mycoloursP[26]]<-"Oligo_Elder"
names(keyvals.col)[keyvals.col == mycoloursP[16]]<-"OPC_Fir"
names(keyvals.col)[keyvals.col == mycoloursP[17]]<-"Oligo_Maple"
names(keyvals.col)[keyvals.col == mycoloursP[18]]<-"Oligo_Oak"
names(keyvals.col)[keyvals.col == mycoloursP[19]]<-"Oligo_Pine"
names(keyvals.col)[keyvals.col == mycoloursP[22]]<-"Oligo_Rowan"

keyvals.shape <- ifelse(
  oligos$Region == "CN", 17,
  ifelse(oligos$Region == "HC", 16,
         15))
names(keyvals.shape)[keyvals.shape == 15] <- 'FrCx'
names(keyvals.shape)[keyvals.shape == 17] <- 'CN'
names(keyvals.shape)[keyvals.shape == 16] <- 'HC'




#PDE1A plot
pde<- EnhancedVolcano(oligos,
                lab = oligos$gene,
                x = "avg_log2FC",
                y = "p_val_adj", 
                labSize = 3.5,
                FCcutoff = 0.8,
                pCutoff = 0.05,
                pointSize = 3,
                raster = F,
                shapeCustom = keyvals.shape,
                colCustom = keyvals.col,
                selectLab = "PDE1A",
                legendPosition = "right",
                boxedLabels = T,         
                drawConnectors = T,
                legendLabSize = 12,
                labFace = "bold",
                title = NULL,
                subtitle =NULL,
                xlim = c((min(oligos$avg_log2FC) - .05), (max(oligos$avg_log2FC + 0.5))))

#oligo plot no labels
p5 <- EnhancedVolcano(oligos,
                lab = NA,
                x = "avg_log2FC",
                y = "p_val_adj", 
                labSize = 3.5,
                FCcutoff = 0.8,
                pCutoff = 0.05,
                pointSize = 3,
                raster = F,
                shapeCustom = keyvals.shape,
                colCustom = keyvals.col,
                #selectLab = "PDE1A",
                #boxedLabels = T,         
                #drawConnectors = T,
                #labFace = "bold",
                title = NULL,
                subtitle =NULL,
                legendLabSize = 12,
                legendIconSize = 4,
                legendPosition = "right",
                xlim = c((min(oligos$avg_log2FC) - .05), (max(oligos$avg_log2FC + 0.5))))

top5 <- oligos %>% top_n(5, abs(avg_log2FC))
for (i in 1:length(oligos$X.1)){
  ifelse(oligos$X.1[i] %in% top5$X.1 == TRUE, oligos$X.1[i] <- oligos$gene[i], oligos$X.1[i] <- oligos$X.1[i])
}

top5$X.1 <- top5$gene

p6 <- EnhancedVolcano(oligos,
                lab = oligos$X.1,
                x = "avg_log2FC",
                y = "p_val_adj", 
                labSize = 3.5,
                FCcutoff = 0.8,
                pCutoff = 0.05,
                pointSize = 3,
                raster = F,
                shapeCustom = keyvals.shape,
                colCustom = keyvals.col,
                selectLab = top5$X.1,
                boxedLabels = T,         
                drawConnectors = T,
                labFace = "bold",
                title = NULL,
                subtitle =NULL,
                legendLabSize = 12,
                legendIconSize = 4,
                legendPosition = "right",
                xlim = c((min(oligos$avg_log2FC) - .05), (max(oligos$avg_log2FC + 0.5))))

top5
```
##oligos w CB
```{r}
oligosCB <- read.csv("M:/PhD/Year 4/10X_HD/04_DGE_condition_tissue_split/within_cluster/condition/Oligos_condition_DEGs_wCB.csv")
for(i in 1:length(oligosCB$ol_clu)){
  oligosCB$Region[i] <- strsplit(oligosCB$ol_clu, "_")[[i]][1]
  oligosCB$Cluster[i] <- strsplit(oligosCB$ol_clu, "_")[[i]][3]
}

ggplot(oligosCB, aes(avg_log2FC, -log10(p_val_adj), label = gene, col = Cluster, shape = Region)) + 
  geom_point(size = 2) + geom_hline(yintercept = 1, aes(linetype = dashed)) + theme_classic() + scale_colour_manual(values = mycoloursP[10:40])


keyvals.col <- ifelse(
  oligosCB$Cluster == "apple", mycoloursP[10],
  ifelse(oligosCB$Cluster == "ash", mycoloursP[11],
         ifelse(oligosCB$Cluster =="birch", mycoloursP[12],
         ifelse(oligosCB$Cluster =="cedar", mycoloursP[24],
                ifelse(oligosCB$Cluster == "cherry", mycoloursP[14],
                       ifelse(oligosCB$Cluster == "elder", mycoloursP[26],
                              ifelse(oligosCB$Cluster =="fir", mycoloursP[16],
                                     ifelse(oligosCB$Cluster =="maple", mycoloursP[17],
                                            ifelse(oligosCB$Cluster == "oak", mycoloursP[18],
                                                   ifelse(oligosCB$Cluster == "pine", mycoloursP[19], mycoloursP[22]
                                                          ))))))))))

names(keyvals.col)[keyvals.col == mycoloursP[10]] <- 'COP_Apple'
names(keyvals.col)[keyvals.col == mycoloursP[11]] <- 'Oligo_Ash'
names(keyvals.col)[keyvals.col == mycoloursP[12]] <- "Oligo_Birch"
names(keyvals.col)[keyvals.col == mycoloursP[24]] <- "Oligo_Cedar"
names(keyvals.col)[keyvals.col == mycoloursP[14]]<-"COP_Cherry"
names(keyvals.col)[keyvals.col == mycoloursP[26]]<-"Oligo_Elder"
names(keyvals.col)[keyvals.col == mycoloursP[16]]<-"OPC_Fir"
names(keyvals.col)[keyvals.col == mycoloursP[17]]<-"Oligo_Maple"
names(keyvals.col)[keyvals.col == mycoloursP[18]]<-"Oligo_Oak"
names(keyvals.col)[keyvals.col == mycoloursP[19]]<-"Oligo_Pine"
names(keyvals.col)[keyvals.col == mycoloursP[22]]<-"Oligo_Rowan"

keyvals.shape <- ifelse(
  oligosCB$Region == "CN", 17,
  ifelse(oligosCB$Region == "HC", 16,
ifelse(oligosCB$Region == "FrCx", 15, 18)))

names(keyvals.shape)[keyvals.shape == 15] <- 'FrCx'
names(keyvals.shape)[keyvals.shape == 17] <- 'CN'
names(keyvals.shape)[keyvals.shape == 16] <- 'HC'
names(keyvals.shape)[keyvals.shape == 18] <- 'CB'


#PDE1A plot
CB_pde<- EnhancedVolcano(oligosCB,
                lab = oligosCB$gene,
                x = "avg_log2FC",
                y = "p_val_adj", 
                labSize = 3.5,
                FCcutoff = 0.8,
                pCutoff = 0.05,
                pointSize = 3,
                raster = F,
                shapeCustom = keyvals.shape,
                colCustom = keyvals.col,
                selectLab = "PDE1A",
                legendPosition = "right",
                boxedLabels = T,         
                drawConnectors = T,
                legendLabSize = 12,
                labFace = "bold",
                title = NULL,
                subtitle =NULL,
                xlim = c((min(oligosCB$avg_log2FC) - .05), (max(oligosCB$avg_log2FC + 0.5))))

#oligo plot no labels
CB_p5 <- EnhancedVolcano(oligosCB,
                lab = NA,
                x = "avg_log2FC",
                y = "p_val_adj", 
                labSize = 3.5,
                FCcutoff = 0.8,
                pCutoff = 0.05,
                pointSize = 3,
                raster = F,
                shapeCustom = keyvals.shape,
                colCustom = keyvals.col,
                #selectLab = "PDE1A",
                #boxedLabels = T,         
                #drawConnectors = T,
                #labFace = "bold",
                title = NULL,
                subtitle =NULL,
                legendLabSize = 12,
                legendIconSize = 4,
                legendPosition = "right",
                xlim = c((min(oligosCB$avg_log2FC) - .05), (max(oligosCB$avg_log2FC + 0.5))))

top5 <- oligosCB %>% top_n(5, abs(avg_log2FC))
for (i in 1:length(oligosCB$X.1)){
  ifelse(oligosCB$X.1[i] %in% top5$X.1 == TRUE, oligosCB$X.1[i] <- oligosCB$gene[i], oligosCB$X.1[i] <- oligosCB$X.1[i])
}

top5$X.1 <- top5$gene

CB_p6 <- EnhancedVolcano(oligosCB,
                lab = oligosCB$X.1,
                x = "avg_log2FC",
                y = "p_val_adj", 
                labSize = 3.5,
                FCcutoff = 0.8,
                pCutoff = 0.05,
                pointSize = 3,
                raster = F,
                shapeCustom = keyvals.shape,
                colCustom = keyvals.col,
                selectLab = top5$X.1,
                boxedLabels = T,         
                drawConnectors = T,
                labFace = "bold",
                title = NULL,
                subtitle =NULL,
                legendLabSize = 12,
                legendIconSize = 4,
                legendPosition = "right",
                xlim = c((min(oligosCB$avg_log2FC) - .05), (max(oligosCB$avg_log2FC + 0.5))))

top5
```


#ENs
```{r}
for(i in 1:length(ENs$en_clu)){
  ENs$Region[i] <- strsplit(ENs$en_clu, "_")[[i]][1]
  ENs$Cluster[i] <- paste0(strsplit(ENs$en_clu, "_")[[i]][2],"_", strsplit(ENs$en_clu, "_")[[i]][3])
}


keyvals.col <- ifelse(
  ENs$Cluster == "Ex_1", mycoloursP[10],
  ifelse(ENs$Cluster == "Ex_2", mycoloursP[11],
         ifelse(ENs$Cluster =="Ex_3", mycoloursP[12],
                ifelse(ENs$Cluster =="Ex_4", mycoloursP[24],
                       ifelse(ENs$Cluster == "Ex_5", mycoloursP[14],
                              ifelse(ENs$Cluster == "Ex_6", mycoloursP[26],
                                     ifelse(ENs$Cluster =="Ex_7", mycoloursP[16],
                                            ifelse(ENs$Cluster =="Ex_8", mycoloursP[17],
                                                    ifelse(ENs$Cluster == "Ex_9", mycoloursP[18],
                                                           ifelse(ENs$Cluster == "Granule_1",mycoloursP[19], 
                                                                  ifelse(ENs$Cluster == "Granule_2",mycoloursP[22],
                                                                         mycoloursP[9])))))))))))

names(keyvals.col)[keyvals.col == mycoloursP[10]] <- 'Ex_1_cx'
names(keyvals.col)[keyvals.col == mycoloursP[11]] <- 'Ex_2_cx'
names(keyvals.col)[keyvals.col == mycoloursP[12]] <- "Ex_3"
names(keyvals.col)[keyvals.col == mycoloursP[24]] <- "Ex_4"
names(keyvals.col)[keyvals.col == mycoloursP[14]]<-"Ex_5_cx"
names(keyvals.col)[keyvals.col == mycoloursP[26]]<-"Ex_6_cx"
names(keyvals.col)[keyvals.col == mycoloursP[16]]<-"Ex_7_cx"
names(keyvals.col)[keyvals.col == mycoloursP[17]]<-"Ex_8_cx"
names(keyvals.col)[keyvals.col == mycoloursP[18]]<-"Ex_9_hc"
names(keyvals.col)[keyvals.col == mycoloursP[19]]<-"Granule_1"
names(keyvals.col)[keyvals.col == mycoloursP[22]]<-"Granule_2"
names(keyvals.col)[keyvals.col == mycoloursP[9]] <- "Granule_3"

keyvals.shape <- ifelse(
  ENs$Region == "CN", 17,
  ifelse(ENs$Region == "HC", 16,
         ifelse(ENs$Region == "FrCx", 15, 18)))

names(keyvals.shape)[keyvals.shape == 15] <- 'FrCx'
names(keyvals.shape)[keyvals.shape == 17] <- 'CN'
names(keyvals.shape)[keyvals.shape == 16] <- 'HC'
names(keyvals.shape)[keyvals.shape == 18] <- 'CB'

#no labels
p7 <- EnhancedVolcano(ENs,
                lab = NA,
                x = "avg_log2FC",
                y = "p_val_adj", 
                labSize = 3.5,
                FCcutoff = 0.8,
                pCutoff = 0.05,
                pointSize = 3,
                raster = F,
                shapeCustom = keyvals.shape,
                colCustom = keyvals.col,
                #selectLab = "PDE1A",
                #boxedLabels = T,         
                #drawConnectors = T,
                #labFace = "bold",
                title = NULL,
                subtitle =NULL,
                legendLabSize = 12,
                legendIconSize = 4,
                legendPosition = "right",
                xlim = c((min(ENs$avg_log2FC) - .05), (max(ENs$avg_log2FC + 0.5))))


top5 <- ENs %>% top_n(5, abs(avg_log2FC))
for (i in 1:length(ENs$X.1)){
  ifelse(ENs$X.1[i] %in% top5$X.1 == TRUE, ENs$X.1[i] <- ENs$gene[i], ENs$X.1[i] <- ENs$X.1[i])
}

top5$X.1 <- top5$gene

#with labels
p8 <- EnhancedVolcano(ENs,
                lab = ENs$X.1,
                x = "avg_log2FC",
                y = "p_val_adj", 
                labSize = 3.5,
                FCcutoff = 0.8,
                pCutoff = 0.05,
                pointSize = 3,
                raster = F,
                shapeCustom = keyvals.shape,
                colCustom = keyvals.col,
                selectLab = top5$X.1,
                boxedLabels = T,         
                drawConnectors = T,
                labFace = "bold",
                title = NULL,
                subtitle =NULL,
                legendLabSize = 12,
                legendIconSize = 4,
                legendPosition = "right",
                xlim = c((min(ENs$avg_log2FC) - .05), (max(ENs$avg_log2FC + 0.5))))
top5
```
#INs
```{r}
for(i in 1:length(INs$in_clu)){
  INs$Region[i] <- strsplit(INs$in_clu, "_")[[i]][1]
  INs$Cluster[i] <- strsplit(INs$in_clu, "_")[[i]][3]
}


keyvals.col <- ifelse(
  INs$Cluster == "1", mycoloursP[10],
  ifelse(INs$Cluster == "2", mycoloursP[11],
         ifelse(INs$Cluster =="3", mycoloursP[12],
                ifelse(INs$Cluster =="4", mycoloursP[24],
                       ifelse(INs$Cluster == "5", mycoloursP[14],
                              ifelse(INs$Cluster == "6", mycoloursP[26],
                                     ifelse(INs$Cluster =="7", mycoloursP[16],
                                            ifelse(INs$Cluster =="8", mycoloursP[17],
                                                   ifelse(INs$Cluster == "9", mycoloursP[18],
                                                          ifelse(INs$Cluster == "10",mycoloursP[19], 
                                                                 ifelse(INs$Cluster == "11",mycoloursP[22],
                                                                        mycoloursP[9])))))))))))

names(keyvals.col)[keyvals.col == mycoloursP[10]] <- 'IN_1_cn'
names(keyvals.col)[keyvals.col == mycoloursP[11]] <- 'IN_2'
names(keyvals.col)[keyvals.col == mycoloursP[12]] <- "IN_3_cx"
names(keyvals.col)[keyvals.col == mycoloursP[24]] <- "IN_4_cx"
names(keyvals.col)[keyvals.col == mycoloursP[14]]<-"IN_5_cx"
names(keyvals.col)[keyvals.col == mycoloursP[26]]<-"IN_6_cb"
names(keyvals.col)[keyvals.col == mycoloursP[16]]<-"IN_7_cx"
names(keyvals.col)[keyvals.col == mycoloursP[17]]<-"IN_8_cx"
names(keyvals.col)[keyvals.col == mycoloursP[18]]<-"IN_9_cn"
names(keyvals.col)[keyvals.col == mycoloursP[19]]<-"IN_10_cn"
names(keyvals.col)[keyvals.col == mycoloursP[22]]<-"IN_11"
names(keyvals.col)[keyvals.col == mycoloursP[9]] <- "IN_12_cn"

keyvals.shape <- ifelse(
  INs$Region == "CN", 17,
  ifelse(INs$Region == "HC", 16,
         ifelse(INs$Region == "FrCx", 15, 18)))

names(keyvals.shape)[keyvals.shape == 15] <- 'FrCx'
names(keyvals.shape)[keyvals.shape == 17] <- 'CN'
names(keyvals.shape)[keyvals.shape == 16] <- 'HC'
names(keyvals.shape)[keyvals.shape == 18] <- 'CB'

#no labels
p9 <- EnhancedVolcano(INs,
                lab = NA,
                x = "avg_log2FC",
                y = "p_val_adj", 
                labSize = 3.5,
                FCcutoff = 0.8,
                pCutoff = 0.05,
                pointSize = 3,
                raster = F,
                shapeCustom = keyvals.shape,
                colCustom = keyvals.col,
                #selectLab = "PDE1A",
                #boxedLabels = T,         
                #drawConnectors = T,
                #labFace = "bold",
                title = NULL,
                subtitle =NULL,
                legendLabSize = 12,
                legendIconSize = 4,
                legendPosition = "right",
                xlim = c((min(INs$avg_log2FC) - .05), (max(INs$avg_log2FC + 0.5))))

top5 <- INs %>% top_n(5, abs(avg_log2FC))
for (i in 1:length(INs$X.1)){
  ifelse(INs$X.1[i] %in% top5$X.1 == TRUE, INs$X.1[i] <- INs$gene[i], INs$X.1[i] <- INs$X.1[i])
}

top5$X.1 <- top5$gene

#with labels
p10 <- EnhancedVolcano(INs,
                lab = INs$X.1,
                x = "avg_log2FC",
                y = "p_val_adj", 
                labSize = 3.5,
                FCcutoff = 0.8,
                pCutoff = 0.05,
                pointSize = 3,
                raster = F,
                shapeCustom = keyvals.shape,
                colCustom = keyvals.col,
                selectLab = top5$X.1,
                boxedLabels = T,         
                drawConnectors = T,
                labFace = "bold",
                title = NULL,
                subtitle =NULL,
                legendLabSize = 12,
                legendIconSize = 4,
                legendPosition = "right",
                xlim = c((min(INs$avg_log2FC) - .05), (max(INs$avg_log2FC + 0.5))))

top5
```

#save plots
```{r}
PlotList<- list()
PlotList[[1]]<-p1
PlotList[[2]]<-p3
PlotList[[3]]<-p5
PlotList[[4]]<-p7
PlotList[[5]]<-p9

pdf(here("PhD","Thesis","thesisplots","20220816_volcanoplots_nolab.pdf"), width = 8, height = 6)
print(PlotList)
dev.off()

PlotList2<- list()
PlotList2[[1]]<-p2
PlotList2[[2]]<-p4
PlotList2[[3]]<-p6
PlotList2[[4]]<-p8
PlotList2[[5]]<-p10
pdf(here("PhD","Thesis","thesisplots","20220816_volcanoplots_withlab.pdf"), width = 8, height = 6)
print(PlotList2)
dev.off()


pdf(here("PhD","Thesis","thesisplots","20220816_volcanoplot_PDE1A.pdf"), width = 8, height = 6)
print(pde)
dev.off()


PlotList3<- list()
PlotList3[[1]]<-CB_p5
PlotList3[[2]]<-CB_p6
PlotList3[[3]]<-CB_pde

pdf(here("PhD","Thesis","thesisplots","20221010_volcanoplots_oligos_wCB.pdf"), width = 8, height = 6)
print(PlotList3)
dev.off()

```